# This workflow lints PR's and automerges Dependabot PR's

name: LintPR & Dependabot

on:
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

# permissions:
#   checks: write
#   pull-requests: write
#   â€¦

# "When the permissions key is used, all unspecified permissions are set to no access."
# Make sure you know all the permissions well, otherwise errors will keep popping up and bothering you.
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token


jobs:
  run-linters-pull-request:
    name: Run linter for pull request
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: ESLint check
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Whether the workflow run should also fail when linter failures are detected.
          eslint: true
          # Errors will cause a failed workflow, warnings are okay, because they will be automatically fixed when the workflow gets merged into the main branch.
          # eslint_args: "--max-warnings 0"
          # https://github.community/t/github-linting-remote-rejected
          # When auto_fix is enabled for the Lint workflow, no linter is allowed to modify the files in .github/workflows. To avoid a failed workflow, we limit the linter to js,ts files.
          eslint_extensions: js,ts
          # prettier will do its job when merging
          # prettier: true
          # prettier_extensions: xml
          # auto_fix must be set to false for the moment  https://github.com/wearerequired/lint-action/issues/13
          auto_fix: false
          continue_on_error: false

  approve-merge:
  # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request
    name: Dependabot approve&merge
    runs-on: ubuntu-latest
    # Not requiring successful prior job
    if: ${{ always() && github.actor == 'dependabot[bot]' }}
    needs: [run-linters-pull-request]
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto-approve PR
        id: approve
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Auto-merge PR
        if: ${{ steps.approve.conclusion == 'success' }}
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
